services:
  nginx:
    image: nginx:1.25-alpine
    container_name: return7-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - spring-net

  backend:
    image: corqu/return7-backend:latest
    container_name: backend
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - spring-net
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DB_URL}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      GOOGLE_API_ID: ${GOOGLE_API_ID}
      GOOGLE_API_SECRET: ${GOOGLE_API_SECRET}
      NAVER_API_ID: ${NAVER_API_ID}
      NAVER_API_SECRET: ${NAVER_API_SECRET}
      KAKAO_API_ID: ${KAKAO_API_ID}
      KAKAO_API_SECRET: ${KAKAO_API_SECRET}
      GMAIL_APP_USERNAME: ${GMAIL_APP_USERNAME}
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}
    depends_on:
      - db
    restart: on-failure

  frontend:
    image: corqu/return7-frontend:latest
    container_name: frontend
    expose:
      - "3000"
    networks:
      - spring-net
    depends_on:
      - backend
    env_file:
      - .env

  db:
    image: mysql:8.0
    container_name: return7-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    restart: on-failure
    networks:
      - spring-net

networks:
  spring-net:
