spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boarddb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: devuser
    password: devpass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


